// Builds design tokens into three outputs:
//   src/styles/tokens.css         - runtime CSS variables (--st-*), one block per theme
//   src/styles/tailwind-theme.css - Tailwind v4 @theme mapping onto those variables
//   src/tokens/tokens.generated.json - flat token list used by the Foundations docs
//
// Light and dark are resolved separately against the same core file, so each
// theme can be edited on its own. Components never see raw values - only the
// semantic names, which exist in both themes.

import StyleDictionary from 'style-dictionary';
import { mkdir, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const CORE = 'tokens/core/**/*.json';
const THEMES_DIR = path.join(ROOT, 'tokens/themes');
const PREFIX = 'st';

// Which token groups are exposed to Tailwind, and under which namespace.
// "palette" is deliberately NOT exposed: components use semantic colours only.
const TAILWIND_NAMESPACE = {
  color: 'color',
  spacing: 'spacing',
  radius: 'radius',
  font: 'font',
  text: 'text',
  shadow: 'shadow',
};

// Groups that differ per theme. Everything else is shared and written to :root once.
const THEMED = new Set(['color', 'shadow']);

const kebab = (parts) => parts.join('-').replace(/\./g, '_');
const cssVar = (token) => `--${PREFIX}-${kebab(token.path)}`;

async function resolveTheme(themeFile) {
  const sd = new StyleDictionary({
    source: [CORE, `tokens/themes/${themeFile}`],
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: { css: { transformGroup: 'css' } },
  });
  const { allTokens } = await sd.getPlatformTokens('css');
  return allTokens;
}

function block(selector, tokens) {
  const lines = tokens.map((t) => `  ${cssVar(t)}: ${t.$value ?? t.value};`);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
}

async function main() {
  process.chdir(ROOT);
  const themeFiles = (await readdir(THEMES_DIR)).filter((f) => f.endsWith('.json'));
  const themes = {};
  for (const file of themeFiles) themes[path.basename(file, '.json')] = await resolveTheme(file);

  if (!themes.light || !themes.dark) throw new Error('Expected tokens/themes/light.json and dark.json');

  // Check both themes define the same semantic names - a missing token in one
  // theme would otherwise fail silently at runtime.
  const semanticNames = (list) => new Set(list.filter((t) => THEMED.has(t.path[0])).map(cssVar));
  const lightNames = semanticNames(themes.light);
  const darkNames = semanticNames(themes.dark);
  const onlyLight = [...lightNames].filter((n) => !darkNames.has(n));
  const onlyDark = [...darkNames].filter((n) => !lightNames.has(n));
  if (onlyLight.length || onlyDark.length) {
    throw new Error(
      `Light and dark themes are out of sync.\n  Only in light: ${onlyLight.join(', ') || '-'}\n  Only in dark: ${onlyDark.join(', ') || '-'}`
    );
  }

  const isCore = (t) => !THEMED.has(t.path[0]);
  const header = '/* Generated by scripts/build-tokens.mjs - do not edit by hand. */\n\n';

  // 1. Runtime variables
  let css = header;
  css += block(':root', themes.light.filter(isCore));
  css += '\n' + block(':root,\n[data-theme="light"]', themes.light.filter((t) => !isCore(t)));
  css += '\n' + block('[data-theme="dark"]', themes.dark.filter((t) => !isCore(t)));
  for (const [name, list] of Object.entries(themes)) {
    if (name === 'light' || name === 'dark') continue;
    css += '\n' + block(`[data-theme="${name}"]`, list.filter((t) => !isCore(t)));
  }

  // 2. Tailwind mapping. `inline` makes utilities emit var(--st-*) directly,
  // so switching data-theme swaps every utility at once.
  const twLines = [
    '  --color-*: initial; /* remove Tailwind default palette - tokens only */',
    '  --color-white: #ffffff; /* kept for overlays on solid colour (tiles, sidebar, switch) */',
    '  --color-black: #000000;',
    '  --font-*: initial;',
    '  --shadow-*: initial;',
  ];
  for (const t of themes.light) {
    const ns = TAILWIND_NAMESPACE[t.path[0]];
    if (!ns) continue;
    twLines.push(`  --${ns}-${kebab(t.path.slice(1))}: var(${cssVar(t)});`);
  }
  const tw = `${header}@theme inline {\n${twLines.join('\n')}\n}\n`;

  // 3. Docs data
  const docs = {};
  for (const [name, list] of Object.entries(themes)) {
    docs[name] = list.map((t) => ({
      name: t.path.join('.'),
      group: t.path[0],
      cssVar: cssVar(t),
      tailwind: TAILWIND_NAMESPACE[t.path[0]] ? kebab(t.path.slice(1)) : null,
      value: t.$value ?? t.value,
      type: t.$type ?? t.type,
      description: t.$description ?? t.comment ?? null,
    }));
  }

  await mkdir('src/styles', { recursive: true });
  await mkdir('src/tokens', { recursive: true });
  await writeFile('src/styles/tokens.css', css);
  await writeFile('src/styles/tailwind-theme.css', tw);
  await writeFile('src/tokens/tokens.generated.json', JSON.stringify(docs, null, 2) + '\n');
  console.log(`Tokens built: ${Object.keys(themes).join(', ')} (${themes.light.length} tokens per theme)`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
